version: '3.7'
services:
  cbz-compress:
    container_name: cbzCompress
    build:
      context: https://github.com/Hempflingclub/cbzCompress.git
      args:
        BRANCH_NAME: ${BRANCH_NAME} # specify in .env File
    volumes:
      - ${INPUT_FOLDER}:/app/in
      - ${OUTPUT_FOLDER}:/app/out
    labels:
      autoheal: true
    environment:
      WAIT_TIME: ${WAIT_TIME}
    restart: always